sudo: true
dist: xenial

language: c

addons:
  apt:
    packages:
      - libasound2-dev
      - libbluetooth-dev
      - libbsd-dev
      - libfdk-aac-dev
      - libglib2.0-dev
      - libncurses5-dev
      - libreadline-dev
      - libsbc-dev
      - python3-pip
      - python3-setuptools

before_script:
  - pip3 install ninja meson

script:
  - meson build
  - ninja -C build
  - ninja -C build test
